/*
Design a C program that manages point fee details for a sports facility. Users input the total
number of points, and for each point, the associated fee is collected. The program calculates the
total profit generated by summing up all fees. Error handling ensures negative fees are addressed
appropriately. Provide a code highlighting the steps, including dynamic memory allocation, user
input, profit calculation, and proper memory management.
 */
#include <stdio.h>
#include <stdlib.h>

int main() {
    int n;
    scanf("%d", &n);

    if (n <= 0) {
        printf("Invalid number of points.\n");
        return 1;
    }

    float *fees = (float *)malloc(n * sizeof(float));
    if (fees == NULL) {
        printf("Memory allocation failed.\n");
        return 1;
    }

    float totalProfit = 0.0;
    for (int i = 0; i < n; i++) {
        scanf("%f", &fees[i]);
        if (fees[i] < 0) {
            printf("Negative fee entered at point %d. Fee should be non-negative.\n", i + 1);
            free(fees);
            return 1;
        }
        totalProfit += fees[i];
    }

    printf("Total profit: %.2f\n", totalProfit);

    free(fees);
    return 0;
}
